// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

//go:build tinygo
// +build tinygo

package nano33

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonDc294373DecodeGithubComMerliotMerleExamplesNano33(in *jlexer.Lexer, out *nano33) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Msg":
			out.Msg = string(in.String())
		case "TempC":
			out.TempC = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonDc294373EncodeGithubComMerliotMerleExamplesNano33(out *jwriter.Writer, in nano33) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Msg\":"
		out.RawString(prefix[1:])
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"TempC\":"
		out.RawString(prefix)
		out.Int32(int32(in.TempC))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v nano33) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjsonDc294373EncodeGithubComMerliotMerleExamplesNano33(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v nano33) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonDc294373EncodeGithubComMerliotMerleExamplesNano33(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *nano33) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjsonDc294373DecodeGithubComMerliotMerleExamplesNano33(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *nano33) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonDc294373DecodeGithubComMerliotMerleExamplesNano33(l, v)
}
